export const goods = state =>state.goods   //商品详情
export const carts = state =>state.carts   //购物车
export const orders = state =>state.orders  //订单
export const pays = state =>state.pays     //支付
export const address = state =>state.address  //地址
export const chooseaddress = state =>state.chooseaddress //添加地址
export const ischoose = state =>state.ischoose  //选择地址
export const tabindex = state =>state.tabindex  //组件下标
export const comname = state =>state.comname   //组件名字 
export const ordercur = state =>state.ordercur //当前订单下表
export const ordertab = state =>state.ordertab //订单下表
